CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    changed_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_order_status_history_order ON order_status_history (order_id, changed_at);
