-- Mỗi khách một hội thoại: CSKH ở quy mô này không cần nhiều luồng song song,
-- và một hội thoại duy nhất giúp cả khách lẫn nhân viên khỏi phải chọn luồng.
CREATE TABLE support_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    last_message_at TIMESTAMP(6) NOT NULL
);
CREATE UNIQUE INDEX uk_support_conversations_user ON support_conversations (user_id);
CREATE INDEX idx_support_conversations_recent ON support_conversations (last_message_at DESC);

CREATE TABLE support_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender VARCHAR(16) NOT NULL,
    sender_user_id BIGINT,
    body VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_support_messages_conversation ON support_messages (conversation_id, created_at);
