CREATE TABLE book_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    source VARCHAR(16) NOT NULL,
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    modified_at TIMESTAMP(6)
);

CREATE UNIQUE INDEX uk_book_reviews_user_order_item ON book_reviews (user_id, order_item_id);
CREATE INDEX idx_book_reviews_book_created ON book_reviews (book_id, created_at DESC);
