ALTER TABLE support_conversations
    ADD COLUMN staff_unread_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN customer_unread_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN last_message_preview VARCHAR(2000) NOT NULL DEFAULT '';

CREATE INDEX idx_support_conversations_staff_unread
    ON support_conversations (staff_unread_count)
    WHERE staff_unread_count > 0;

CREATE TABLE support_message_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_support_message_attachments_message
    ON support_message_attachments (message_id);
