CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    fullname VARCHAR(255),
    phone VARCHAR(255),
    birthday DATE,
    iam_id VARCHAR(255),
    customer_tier_id SMALLINT,
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    isbn VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    image_url VARCHAR(255),
    format VARCHAR(255),
    list_price BIGINT,
    rental_price_day BIGINT,
    rental_price_week BIGINT,
    rental_price_month BIGINT,
    deposit_amount BIGINT,
    publish_year SMALLINT,
    publisher VARCHAR(255),
    language VARCHAR(255),
    page_count SMALLINT,
    is_active BOOLEAN,
    PRIMARY KEY (id),
    CONSTRAINT uk_books_isbn UNIQUE (isbn)
);

CREATE TABLE book_copies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    book_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    condition_status VARCHAR(255),
    notes VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE INDEX idx_book_copies_book_status ON book_copies (book_id, status);

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    PRIMARY KEY (id)
);
CREATE INDEX idx_carts_user_id ON carts (user_id);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cart_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    item_type VARCHAR(255) NOT NULL,
    quantity INT,
    rental_term_value INT,
    rental_term_unit VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE INDEX idx_cart_items_cart_id ON cart_items (cart_id);

CREATE TABLE user_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    full_name VARCHAR(255),
    phone VARCHAR(255),
    province VARCHAR(255),
    district VARCHAR(255),
    ward VARCHAR(255),
    address_detail VARCHAR(255),
    is_default BOOLEAN,
    PRIMARY KEY (id)
);
CREATE INDEX idx_user_addresses_user_id ON user_addresses (user_id);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    order_code VARCHAR(255) NOT NULL,
    order_type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    payment_status VARCHAR(255) NOT NULL,
    payment_method VARCHAR(255) NOT NULL,
    total_items INT,
    total_amount BIGINT,
    total_deposit BIGINT,
    total_discount BIGINT,
    voucher_id BIGINT,
    shipping_address_id BIGINT,
    notes VARCHAR(255),
    created_at TIMESTAMP(6),
    modified_at TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_orders_order_code UNIQUE (order_code)
);
CREATE INDEX idx_orders_user_status_payment ON orders (user_id, status, payment_status);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    book_copy_id BIGINT,
    item_type VARCHAR(255) NOT NULL,
    quantity INT,
    unit_price BIGINT,
    deposit_amount BIGINT,
    subtotal BIGINT,
    PRIMARY KEY (id)
);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    method VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(255),
    gateway_ref VARCHAR(255),
    paid_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    PRIMARY KEY (id)
);
CREATE INDEX idx_payments_order_created ON payments (order_id, created_at);

CREATE TABLE rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_item_id BIGINT,
    book_copy_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rental_term_unit VARCHAR(255),
    rental_term_value INT,
    deposit_amount BIGINT,
    rental_start_date DATE,
    planned_return_date DATE,
    actual_return_date DATE,
    status VARCHAR(255),
    late_days INT,
    late_fee_amount BIGINT,
    damage_fee_amount BIGINT,
    notes VARCHAR(255),
    created_at TIMESTAMP(6),
    modified_at TIMESTAMP(6),
    PRIMARY KEY (id)
);
CREATE INDEX idx_rentals_user_status ON rentals (user_id, status);
CREATE INDEX idx_rentals_overdue ON rentals (actual_return_date, planned_return_date, status);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    price BIGINT,
    duration_days INT,
    max_rentals INT,
    status VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE INDEX idx_subscriptions_status ON subscriptions (status);

CREATE TABLE customer_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    subscription_id BIGINT NOT NULL,
    start_date DATE,
    end_date DATE,
    used_rentals INT,
    status VARCHAR(255),
    PRIMARY KEY (id)
);
CREATE INDEX idx_customer_subscriptions_user_status_end ON customer_subscriptions (user_id, status, end_date);

CREATE TABLE vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    description VARCHAR(255),
    discount_type VARCHAR(255),
    discount_value BIGINT,
    max_discount_amount BIGINT,
    min_order_amount BIGINT,
    start_at TIMESTAMP(6),
    end_at TIMESTAMP(6),
    usage_limit_total INT,
    usage_limit_per_user INT,
    status SMALLINT,
    PRIMARY KEY (id),
    CONSTRAINT uk_vouchers_code UNIQUE (code)
);

CREATE TABLE voucher_usages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    voucher_id BIGINT NOT NULL,
    user_id BIGINT,
    order_id BIGINT,
    discount_amount BIGINT,
    status VARCHAR(255),
    reserved_at TIMESTAMP(6),
    committed_at TIMESTAMP(6),
    expired_at TIMESTAMP(6),
    PRIMARY KEY (id)
);
CREATE INDEX idx_voucher_usages_order_status ON voucher_usages (order_id, status);
CREATE INDEX idx_voucher_usages_voucher_user_status ON voucher_usages (voucher_id, user_id, status);
CREATE INDEX idx_voucher_usages_status_reserved ON voucher_usages (status, reserved_at);
