ALTER TABLE orders      ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE payments    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE vouchers    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE book_copies ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE vouchers    ADD COLUMN used_count INT NOT NULL DEFAULT 0;
