CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT uk_roles_code UNIQUE (code)
);

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(80) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_permissions_code UNIQUE (code)
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(id),
    permission_id BIGINT NOT NULL REFERENCES permissions(id),
    PRIMARY KEY (role_id, permission_id)
);
CREATE INDEX idx_role_permissions_role_id ON role_permissions (role_id);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    granted_by BIGINT,
    granted_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX idx_user_roles_user_id ON user_roles (user_id);

CREATE TABLE user_permissions (
    user_id BIGINT NOT NULL REFERENCES users(id),
    permission_id BIGINT NOT NULL REFERENCES permissions(id),
    expires_at TIMESTAMP(6),
    PRIMARY KEY (user_id, permission_id)
);
CREATE INDEX idx_user_permissions_user_expires ON user_permissions (user_id, expires_at);

INSERT INTO roles (code, name, description) VALUES
    ('CUSTOMER', 'Customer', 'Customer account'),
    ('SALES_STAFF', 'Sales Staff', 'Sales and rental counter staff'),
    ('WAREHOUSE_MANAGER', 'Warehouse Manager', 'Inventory and book-copy manager'),
    ('ADMIN', 'Administrator', 'System administrator');

INSERT INTO permissions (code) VALUES
    ('book:read'),
    ('order:create'),
    ('order:read:own'),
    ('rental:read:own'),
    ('rental:extend:own'),
    ('subscription:purchase'),
    ('order:read:all'),
    ('order:update-status'),
    ('rental:read:all'),
    ('rental:checkin'),
    ('order:create:counter'),
    ('payment:refund'),
    ('copy:manage'),
    ('stock:receive'),
    ('stock:adjust'),
    ('inventory:audit'),
    ('book:manage'),
    ('voucher:manage'),
    ('subscription:manage'),
    ('user:manage'),
    ('role:assign'),
    ('report:view'),
    ('config:manage');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'book:read', 'order:create', 'order:read:own', 'rental:read:own',
    'rental:extend:own', 'subscription:purchase'
)
WHERE r.code IN ('CUSTOMER', 'SALES_STAFF', 'WAREHOUSE_MANAGER', 'ADMIN');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'order:read:all', 'order:update-status', 'rental:read:all',
    'rental:checkin', 'order:create:counter', 'payment:refund'
)
WHERE r.code IN ('SALES_STAFF', 'ADMIN');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN ('copy:manage', 'stock:receive', 'stock:adjust', 'inventory:audit')
WHERE r.code IN ('WAREHOUSE_MANAGER', 'ADMIN');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'book:manage', 'voucher:manage', 'subscription:manage',
    'user:manage', 'role:assign', 'report:view', 'config:manage'
)
WHERE r.code = 'ADMIN';

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
CROSS JOIN roles r
WHERE r.code = 'CUSTOMER';

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT uk_categories_name UNIQUE (name),
    CONSTRAINT uk_categories_slug UNIQUE (slug)
);

CREATE TABLE book_categories (
    book_id BIGINT NOT NULL REFERENCES books(id),
    category_id BIGINT NOT NULL REFERENCES categories(id),
    PRIMARY KEY (book_id, category_id)
);
CREATE INDEX idx_book_categories_category_book ON book_categories (category_id, book_id);
