CREATE TABLE rental_fulfillments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INT NOT NULL DEFAULT 0,
    error_message VARCHAR(1000),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_rental_fulfillments_order_id UNIQUE (order_id)
);

CREATE INDEX idx_rental_fulfillments_retry
    ON rental_fulfillments (status, updated_at);
