ALTER TABLE payments ADD COLUMN transfer_reference VARCHAR(32);
ALTER TABLE payments ADD COLUMN expires_at TIMESTAMP(6);
CREATE UNIQUE INDEX uk_payments_transfer_reference ON payments (transfer_reference) WHERE transfer_reference IS NOT NULL;
CREATE INDEX idx_payments_bank_transfer_expiry ON payments (method, status, expires_at);

CREATE TABLE processed_bank_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(255) NOT NULL,
    bank_txn_ref VARCHAR(255),
    processed_at TIMESTAMP(6) NOT NULL
);
CREATE UNIQUE INDEX uk_processed_bank_messages_message_id ON processed_bank_messages (message_id);
CREATE UNIQUE INDEX uk_processed_bank_messages_txn_ref ON processed_bank_messages (bank_txn_ref) WHERE bank_txn_ref IS NOT NULL;

CREATE TABLE unmatched_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(255) NOT NULL,
    bank_txn_ref VARCHAR(255),
    payment_reference VARCHAR(32),
    amount BIGINT,
    received_at TIMESTAMP(6),
    reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX idx_unmatched_transfers_created_at ON unmatched_transfers (created_at);
