CREATE TABLE blog_posts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slug            VARCHAR(255) NOT NULL,
    title           VARCHAR(255) NOT NULL,
    excerpt         VARCHAR(500),
    content         TEXT NOT NULL,
    cover_image_url VARCHAR(500),
    status          VARCHAR(20)  NOT NULL,
    book_id         BIGINT,
    author_id       BIGINT,
    published_at    TIMESTAMP(6),
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_blog_posts_slug UNIQUE (slug)
);

CREATE INDEX idx_blog_posts_status_published_at ON blog_posts (status, published_at DESC);
CREATE INDEX idx_blog_posts_book_id ON blog_posts (book_id);
